### ISSUE TITLE
Protected Workflows

### ISSUE THREAD

**Issue by eladchen** [fiftysevenmedia/spendable#439]
Hi - I was wondering if you're able to use protected workflows as expected?

I'm the author of the bot.

**Comment by michaelst** [comment]
It hasn’t been working that well for me. It keeps canceling all of my
workflows even though I added my username on anyEvent

**Comment by eladchen** [comment]
Any chance we can meet and figure out why?

**Comment by michaelst** [comment]
Sure message me on twitter https://twitter.com/michaelst57
